In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder

In [ ]:
df = pd.read_csv('titanic_data_updated.csv')

In [ ]:
df.drop(['PassengerId','Name','Ticket'],axis = 1, inplace=True)
df

    Survived  Pclass     Sex   Age  SibSp  Parch     Fare Cabin Embarked
0         no   third    male  22.0      1      0   7.2500   NaN        S
1        yes   first  female  38.0      1      0  71.2833   C85        C
2        yes   third  female  26.0      0      0   7.9250   NaN        S
3        yes   first  female  35.0      1      0  53.1000  C123        S
4         no   third    male  35.0      0      0   8.0500   NaN        S
..       ...     ...     ...   ...    ...    ...      ...   ...      ...
886       no  second    male  27.0      0      0  13.0000   NaN        S
887      yes   first  female  19.0      0      0  30.0000   B42        S
888       no   third  female   NaN      1      2  23.4500   NaN        S
889      yes   first    male  26.0      0      0  30.0000  C148        C
890       no   third    male  32.0      0      0   7.7500   NaN        Q

[891 rows x 9 columns]

In [ ]:
df.isnull().sum()

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Cabin       687
Embarked      2
dtype: int64

In [ ]:
X = df.drop(['Survived'],axis=1)
X

     Pclass     Sex   Age  SibSp  Parch     Fare Cabin Embarked
0     third    male  22.0      1      0   7.2500   NaN        S
1     first  female  38.0      1      0  71.2833   C85        C
2     third  female  26.0      0      0   7.9250   NaN        S
3     first  female  35.0      1      0  53.1000  C123        S
4     third    male  35.0      0      0   8.0500   NaN        S
..      ...     ...   ...    ...    ...      ...   ...      ...
886  second    male  27.0      0      0  13.0000   NaN        S
887   first  female  19.0      0      0  30.0000   B42        S
888   third  female   NaN      1      2  23.4500   NaN        S
889   first    male  26.0      0      0  30.0000  C148        C
890   third    male  32.0      0      0   7.7500   NaN        Q

[891 rows x 8 columns]

In [ ]:
y = df['Survived']
y

0       no
1      yes
2      yes
3      yes
4       no
      ...
886     no
887    yes
888     no
889    yes
890     no
Name: Survived, Length: 891, dtype: object

In [ ]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [ ]:
X_train
display(y_train)

331     no
733     no
382     no
704     no
813     no
      ...
106    yes
270     no
860     no
435    yes
102     no
Name: Survived, Length: 712, dtype: object

In [ ]:
# test korar jonno
X_test
display(y_test)

709    yes
439     no
840     no
720    yes
39     yes
      ...
433     no
773     no
25     yes
84     yes
10     yes
Name: Survived, Length: 179, dtype: object

In [ ]:
# full the missing value is called imputing
X_train.isnull().sum()

Pclass        0
Sex           0
Age         140
SibSp         0
Parch         0
Fare          0
Cabin       553
Embarked      2
dtype: int64

In [ ]:
X_test.isnull().sum()

Pclass        0
Sex           0
Age          37
SibSp         0
Parch         0
Fare          0
Cabin       134
Embarked      0
dtype: int64

In [ ]:
#Mean Imutation
age_mean = X_train['Age'].mean() #Meadn ber kora
X_train['mean_age'] = X_train['Age'].fillna(age_mean) #impute code
X_test['mean_age'] = X_test['Age'].fillna(age_mean)
X_train

     Pclass     Sex   Age  SibSp  Parch      Fare    Cabin Embarked   mean_age
331   first    male  45.5      0      0   28.5000     C124        S  45.500000
733  second    male  23.0      0      0   13.0000      NaN        S  23.000000
382   third    male  32.0      0      0    7.9250      NaN        S  32.000000
704   third    male  26.0      1      0    7.8542      NaN        S  26.000000
813   third  female   6.0      4      2   31.2750      NaN        S   6.000000
..      ...     ...   ...    ...    ...       ...      ...      ...        ...
106   third  female  21.0      0      0    7.6500      NaN        S  21.000000
270   first    male   NaN      0      0   31.0000      NaN        S  29.498846
860   third    male  41.0      2      0   14.1083      NaN        S  41.000000
435   first  female  14.0      1      2  120.0000  B96 B98        S  14.000000
102   first    male  21.0      0      1   77.2875      D26        S  21.000000

[712 rows x 9 columns]

In [ ]:
#median imputatuon

age_median = X_train['Age'].median() #median ber korar jonno
X_train['median_age'] = X_train['Age'].fillna(age_median)
X_test['median_age'] = X_test['Age'].fillna(age_median)
X_train

,Pclass,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked,mean_age,median_age
331,first,male,45.5,0,0,28.5000,C124,S,45.500000,45.5
733,second,male,23.0,0,0,13.0000,NaN,S,23.000000,23.0
382,third,male,32.0,0,0,7.9250,NaN,S,32.000000,32.0
704,third,male,26.0,1,0,7.8542,NaN,S,26.000000,26.0
813,third,female,6.0,4,2,31.2750,NaN,S,6.000000,6.0
...,...,...,...,...,...,...,...,...,...,...
106,third,female,21.0,0,0,7.6500,NaN,S,21.000000,21.0
270,first,male,NaN,0,0,31.0000,NaN,S,29.498846,28.0
860,third,male,41.0,2,0,14.1083,NaN,S,41.000000,41.0
435,first,female,14.0,1,2,120.0000,B96 B98,S,14.000000,14.0
102,first,male,21.0,0,1,77.2875,D26,S,21.000000,21.0

In [ ]:
X_train

,Pclass,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked,mean_age,median_age
331,first,male,45.5,0,0,28.5000,C124,S,45.500000,45.5
733,second,male,23.0,0,0,13.0000,NaN,S,23.000000,23.0
382,third,male,32.0,0,0,7.9250,NaN,S,32.000000,32.0
704,third,male,26.0,1,0,7.8542,NaN,S,26.000000,26.0
813,third,female,6.0,4,2,31.2750,NaN,S,6.000000,6.0
...,...,...,...,...,...,...,...,...,...,...
106,third,female,21.0,0,0,7.6500,NaN,S,21.000000,21.0
270,first,male,NaN,0,0,31.0000,NaN,S,29.498846,28.0
860,third,male,41.0,2,0,14.1083,NaN,S,41.000000,41.0
435,first,female,14.0,1,2,120.0000,B96 B98,S,14.000000,14.0
102,first,male,21.0,0,1,77.2875,D26,S,21.000000,21.0

In [ ]:
X_train.drop(['mean_age','median_age'] , axis=1 , inplace=True)
X_train

     Pclass     Sex   Age  SibSp  Parch      Fare    Cabin Embarked
331   first    male  45.5      0      0   28.5000     C124        S
733  second    male  23.0      0      0   13.0000      NaN        S
382   third    male  32.0      0      0    7.9250      NaN        S
704   third    male  26.0      1      0    7.8542      NaN        S
813   third  female   6.0      4      2   31.2750      NaN        S
..      ...     ...   ...    ...    ...       ...      ...      ...
106   third  female  21.0      0      0    7.6500      NaN        S
270   first    male   NaN      0      0   31.0000      NaN        S
860   third    male  41.0      2      0   14.1083      NaN        S
435   first  female  14.0      1      2  120.0000  B96 B98        S
102   first    male  21.0      0      1   77.2875      D26        S

[712 rows x 8 columns]

**Ordinal Value Encoder**

In [ ]:
pclass_encoder = OrdinalEncoder(categories = [['third','second','first']]) #for ordinal first catagory vag kora
pclass_encoder.fit(X_train[['Pclass']]) #dataset(X_train) a fit korano

X_train['Encoded_pclass'] = pclass_encoder.transform(X_train[['Pclass']]).ravel() #third transform kora
X_test['Encoded_pclass'] = pclass_encoder.transform(X_test[['Pclass']]).ravel()

X_train

,Pclass,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked,Encoded_pclass
331,first,male,45.5,0,0,28.5000,C124,S,2.0
733,second,male,23.0,0,0,13.0000,NaN,S,1.0
382,third,male,32.0,0,0,7.9250,NaN,S,0.0
704,third,male,26.0,1,0,7.8542,NaN,S,0.0
813,third,female,6.0,4,2,31.2750,NaN,S,0.0
...,...,...,...,...,...,...,...,...,...
106,third,female,21.0,0,0,7.6500,NaN,S,0.0
270,first,male,NaN,0,0,31.0000,NaN,S,2.0
860,third,male,41.0,2,0,14.1083,NaN,S,0.0
435,first,female,14.0,1,2,120.0000,B96 B98,S,2.0
102,first,male,21.0,0,1,77.2875,D26,S,2.0

**Nominal Value Encoding**

**One Hot Encoding**

In [ ]:
sex_one = OneHotEncoder(sparse_output=False).set_output(transform='pandas')

encoded_train_df = sex_one.fit_transform(X_train[['Sex']])
encoded_test_df = sex_one.transform(X_test[['Sex']])

X_train = pd.concat([X_train, encoded_train_df], axis=1)
X_test = pd.concat([X_test, encoded_test_df], axis=1)

X_train

,Pclass,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked,Encoded_pclass,Sex_female,Sex_male
331,first,male,45.5,0,0,28.5000,C124,S,2.0,0.0,1.0
733,second,male,23.0,0,0,13.0000,NaN,S,1.0,0.0,1.0
382,third,male,32.0,0,0,7.9250,NaN,S,0.0,0.0,1.0
704,third,male,26.0,1,0,7.8542,NaN,S,0.0,0.0,1.0
813,third,female,6.0,4,2,31.2750,NaN,S,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
106,third,female,21.0,0,0,7.6500,NaN,S,0.0,1.0,0.0
270,first,male,NaN,0,0,31.0000,NaN,S,2.0,0.0,1.0
860,third,male,41.0,2,0,14.1083,NaN,S,0.0,0.0,1.0
435,first,female,14.0,1,2,120.0000,B96 B98,S,2.0,1.0,0.0
102,first,male,21.0,0,1,77.2875,D26,S,2.0,0.0,1.0

In [ ]:
X_train.drop(['Pclass','Sex'],axis=1,inplace=True)

In [ ]:
X_test

,Pclass,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked,mean_age,median_age,Encoded_pclass,Sex_female,Sex_male
709,third,male,NaN,1,1,15.2458,NaN,C,29.498846,28.0,0.0,0.0,1.0
439,second,male,31.0,0,0,10.5000,NaN,S,31.000000,31.0,1.0,0.0,1.0
840,third,male,20.0,0,0,7.9250,NaN,S,20.000000,20.0,0.0,0.0,1.0
720,second,female,6.0,0,1,33.0000,NaN,S,6.000000,6.0,1.0,1.0,0.0
39,third,female,14.0,1,0,11.2417,NaN,C,14.000000,14.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
433,third,male,17.0,0,0,7.1250,NaN,S,17.000000,17.0,0.0,0.0,1.0
773,third,male,NaN,0,0,7.2250,NaN,C,29.498846,28.0,0.0,0.0,1.0
25,third,female,38.0,1,5,31.3875,NaN,S,38.000000,38.0,0.0,1.0,0.0
84,second,female,17.0,0,0,10.5000,NaN,S,17.000000,17.0,1.0,1.0,0.0
10,third,female,4.0,1,1,16.7000,G6,S,4.000000,4.0,0.0,1.0,0.0

**Encode for Embarked**

In [ ]:
embarked_ohe = OneHotEncoder(sparse_output=False).set_output(transform='pandas')

embarked_ohe.fit(X_train[['Embarked']])


encoded_df = embarked_ohe.transform(X_train[['Embarked']])
X_train = pd.concat([X_train,encoded_df],axis =1)

In [ ]:
# transforming test data
encoded_df = embarked_ohe.transform(X_test[['Embarked']])
X_test = pd.concat([X_test,encoded_df],axis =1)

In [ ]:
X_train.sample(10)

,Age,SibSp,Parch,Fare,Cabin,Encoded_pclass,Sex_female,Sex_male,Embarked_C,Embarked_Q,Embarked_S,Embarked_nan
763,36.0,1,2,120.0000,B96 B98,2.0,1.0,0.0,0.0,0.0,1.0,0.0
142,24.0,1,0,15.8500,NaN,0.0,1.0,0.0,0.0,0.0,1.0,0.0
318,31.0,0,2,164.8667,C7,2.0,1.0,0.0,0.0,0.0,1.0,0.0
559,36.0,1,0,17.4000,NaN,0.0,1.0,0.0,0.0,0.0,1.0,0.0
436,21.0,2,2,34.3750,NaN,0.0,1.0,0.0,0.0,0.0,1.0,0.0
27,19.0,3,2,263.0000,C23 C25 C27,2.0,0.0,1.0,0.0,0.0,1.0,0.0
810,26.0,0,0,7.8875,NaN,0.0,0.0,1.0,0.0,0.0,1.0,0.0
851,74.0,0,0,7.7750,NaN,0.0,0.0,1.0,0.0,0.0,1.0,0.0
353,25.0,1,0,17.8000,NaN,0.0,0.0,1.0,0.0,0.0,1.0,0.0
119,2.0,4,2,31.2750,NaN,0.0,1.0,0.0,0.0,0.0,1.0,0.0

In [ ]:
X_train.drop(['Embarked'],axis=1 , inplace= True)

In [ ]:
X_train['Cabin'].value_counts()

Cabin
C23 C25 C27    4
C22 C26        3
F2             3
G6             3
B96 B98        3
              ..
A14            1
D49            1
C87            1
D56            1
C62 C64        1
Name: count, Length: 117, dtype: int64

In [ ]:
y_train

331     no
733     no
382     no
704     no
813     no
      ...
106    yes
270     no
860     no
435    yes
102     no
Name: Survived, Length: 712, dtype: object

**Y label Encoding**

In [ ]:

lable = LabelEncoder()

lable.fit(y_train)
y_train_array = lable.transform(y_train)
y_test_array = lable.transform(y_test)

y_train = pd.Series(y_train_array, index=y_train.index, name=y_train.name)
y_test = pd.Series(y_test_array, index=y_test.index, name=y_test.name)
y_train

331    0
733    0
382    0
704    0
813    0
      ..
106    1
270    0
860    0
435    1
102    0
Name: Survived, Length: 712, dtype: int64